version: '3.4'

services:
  insurancewebapi:
    image: ${DOCKER_REGISTRY-}insurancewebapi
    build:
      context: ./backend
      dockerfile: InsuranceWebApi/Dockerfile
    ports:
        - 3000:8081
    networks:
        - insurancenetwork

  insurancewebapp:
    image: ${DOCKER_REGISTRY-}insurancewebapp
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
        - 8080:80
    networks:
        - insurancenetwork
         
networks:
  insurancenetwork:
    driver: bridge
